version: "3.8"

services:
  traefik:
    image: traefik:v2.8
    networks:
      - internal
    command:
      - --log.level=DEBUG
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `internal`)
      - --entrypoints.http.address=:80
      - --providers.docker
      - --providers.docker.swarmmode
      - --providers.docker.exposedbydefault=false
      - --accesslog
      - --log
      - --api
      - --serverstransport.insecureskipverify=true
      - --tracing.jaeger=true
      - --tracing.jaeger.samplingServerURL=http://opentracing.jaeger.int:5778/sampling
      - --tracing.jaeger.localAgentHostPort=http://opentracing.jaeger.int:6831
      - --tracing.jaeger.traceContextHeaderName=uber-trace-id
      - --tracing.jaeger.collector.endpoint=http://opentracing.jaeger.int:14268/api/traces?format=jaeger.thrift
      - --metrics.influxdb2=true
      - --metrics.influxdb2.address=http://storages.influxdb.int:8086
      - --metrics.influxdb2.token=M9J_67mH_UIHIyuMXNEz2qOVTOGBrBj9WfSNNuzlDH--aqNgO-s6PACFCEzvrMT3MTPzeyAKNpXuEZYPFLI3CA==
      - --metrics.influxdb2.org=influx_demo_org
      - --metrics.influxdb2.bucket=traefik_bucket
      - --metrics.influxdb2.addEntryPointsLabels=true
      - --metrics.influxdb2.addrouterslabels=true
      - --metrics.influxdb2.addServicesLabels=true
      - dashboard=true
    ports:
      - "80:80"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=internal
        - traefik.constraint-label=internal
        - traefik.http.routers.traefik.rule=Host(`dashboard.traefik.int`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=9999
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  internal:
    external: true
