version: "3.8"

services:
  influxdb:
    networks:
      - internal
    labels:
      app: influxdb
      role: storage
      namespace: infra
    image: influxdb:2.3.0-alpine
    hostname: storages.influxdb.int
    volumes:
      - influxdb_data:/root/.influxdbv2
      - influxdb_db_data:/var/lib/influxdb2
      - influxdb_etc:/etc/influxdb2
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
    restart: always
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=internal
        - traefik.constraint-label=internal
        - traefik.http.routers.influxdb.entrypoints=http
        - traefik.http.services.influxdb.loadbalancer.server.port=8086
        - traefik.http.routers.influxdb.rule=Host(`influxdb.swarm.int`)
        - traefik.http.routers.influxdb.service=influxdb@docker
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.3'
          memory: 256M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.influxdb == yes
    env_file:
      - ${PWD}/../../.env
networks:
  internal:
    external: true

volumes:
  influxdb_data:
    driver: local
  influxdb_db_data:
    driver: local
  influxdb_etc:
    driver: local
