version: "3.8"

services:
  influxdb:
    networks:
      - internal
    image: influxdb:2.3.0-alpine
    hostname: storages.influxdb.int
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/root/.influxdbv2
      - influxdb_db_data:/var/lib/influxdb2
      - influxdb_etc:/etc/influxdb2
    environment:
      - INFLUXDB_DB=influx
      - DOCKER_INFLUXDB_INIT_USERNAME=influx_admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=influx_admin
      - DOCKER_INFLUXDB_INIT_ORG=influx_demo_org
      - DOCKER_INFLUXDB_INIT_BUCKET=influx_demo_bucket
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=internal
        - traefik.constraint-label=internal
        - traefik.http.routers.influxdb.entrypoints=http
        - traefik.http.services.influxdb.loadbalancer.server.port=8086
        - traefik.http.routers.influxdb.rule=Host(`influxdb.swarm.int`)
        - traefik.http.routers.influxdb.service=influxdb@docker
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 750M
        reservations:
          cpus: '0.3'
          memory: 500M
      placement:
        constraints:
          - node.labels.influxdb == yes

networks:
  internal:
    external: true

volumes:
  influxdb_data:
    driver: local
  influxdb_db_data:
    driver: local
  influxdb_etc:
    driver: local
