version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.3.3
    hostname: storage.elasticsearch.int
    networks:
      - internal
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
    deploy:
      placement:
        constraints:
          - node.labels.elasticsearch == yes
      replicas: 1
      resources:
        limits:
          cpus: '1.5'
          memory: 2500M
        reservations:
          cpus: '1'
          memory: 1500M
    volumes:
      - shared-data:/usr/share/elasticsearch/data

networks:
  internal:
    external: true

volumes:
  shared-data:
    driver: local