version: "3.8"

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    hostname: '{{.Node.ID}}'
    networks:
      - internal
    labels:
      app: cadvisor
      role: agent
      namespace: infra
    privileged: true
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

networks:
  internal:
    external: true
