version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.37.6
    hostname: metrics.prometheus.int
    networks:
      - internal
    ports:
      - "9090:9090"
    command: "--config.file=/prometheus.yml"
    user: root
    volumes:
      - ./prometheus.yml:/prometheus.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  internal:
    external: true
