version: "3.8"

services:
  mysql:
    image: mysql:8-oracle
    networks:
      - internal
    labels:
      app: mysql
      role: storage
      namespace: infra
    hostname: storages.mysql.int
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306/tcp"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 750M
        reservations:
          cpus: '0.3'
          memory: 500M
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.mysql == yes
    env_file:
      - ${PWD}/../../.env

networks:
  internal:
    external: true

volumes:
  mysql:
    driver: local