version: "3.8"

services:
  telegraf:
    image: telegraf:1.23.3-alpine
    networks:
      - internal
    environment:
      # Change this token for your env
      - INFLUX_TOKEN=OY7nj_72FVZYkhoNKPA5pmo6Mu8y3nE8H8RYnZ8pLkN4zLEMBbq0B5DVV2_IUqUYMFxK-w4-tstFlcgd74t7eQ==
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    volumes:
      - ${PWD}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  internal:
    external: true
