version: "3.8"

services:
  telegraf:
    image: telegraf:1.23.3-alpine
    networks:
      - internal
    environment:
      # Change this token for your env
      - INFLUX_TOKEN=Dh6dcEKqGLPqWbPWExmISIih45KEIMI0Q2Z0zDjOV41JswIChawxxZtm3vJg6S98n73qm12OktASrcshNBT3fA==
      - HOSTNAME={{.Node.Hostname}}
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    volumes:
      - ${PWD}/telegraf.conf:/etc/telegraf/telegraf.conf:ro

networks:
  internal:
    external: true
